; Exercise 1.9.  Each of the following two procedures defines a method for adding two 
; positive integers in terms of the procedures inc, which increments its argument by 1, 
; and dec, which decrements its argument by 1.

; Definition 1:
; (define (+ a b)
;   (if (= a 0)
;       b
;       (inc (+ (dec a) b))))

; Definition 2:
; (define (+ a b)
;   (if (= a 0)
;       b
;       (+ (dec a) (inc b))))

; Using the substitution model, illustrate the process generated by each procedure in evaluating (+ 4 5). Are these processes iterative or recursive?
;
; -----------------------------------------------------------
;
; Definition 1 expanded by the applicative substitution model
;
; (+ 4 5)
; (inc (+ 3 5))
; (inc (inc (+ 2 5)))
; (inc (inc (inc (+ 1 5))))
; (inc (inc (inc (inc (+ 0 5)))))
; (inc (inc (inc (inc 5))))
; (inc (inc (inc 6)))
; (inc (inc 7))
; (inc 8)
; 9
;
; We clearly see by the shape of the process that it is linear
; recursive process
;
;Definition 2 is expanded like this
;
;(+ 4 5)
;(+ 3 6)
;(+ 2 7)
;(+ 1 8)
;(+ 0 9)
;9
;
; Obviously, it is linear iteration in place here.
